package fr.ufrsciencestech.views;

import javax.swing.*;
import java.lang.*;

/**
 *
 * @author mgall
 */
public class Interface extends javax.swing.JDialog {

    private JList<String> listeFruits1;
    private double prixTotal1;
    
    /**
     * Creates new form Interface
     */
    //public Interface(java.awt.Frame parent, boolean modal, JList<String> listeFruits, double prixTotal ) {
    public Interface(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
        /*
        this.listeFruits1=listeFruits;
        this.prixTotal1=prixTotal;
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterfacePanier = new javax.swing.JPanel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 200), new java.awt.Dimension(20, 200), new java.awt.Dimension(20, 200));
        Colonne1 = new javax.swing.JPanel();
        choixRecette = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        ScrollPaneRecettes = new javax.swing.JScrollPane();
        afficheRecette = new javax.swing.JTextArea();
        filler3 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 200), new java.awt.Dimension(30, 200), new java.awt.Dimension(30, 200));
        Colonne2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelVotrePanier = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ScrollPanePanier = new javax.swing.JScrollPane();
        affichePanier = new javax.swing.JTextArea();
        LigneTotalPanier = new javax.swing.JPanel();
        LabelTotalPanier = new javax.swing.JLabel();
        LabelPrixTotal = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 200), new java.awt.Dimension(30, 200), new java.awt.Dimension(30, 200));
        Colonne3 = new javax.swing.JPanel();
        BoutonAjouterFruit = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        BoutonRetirerFruit = new javax.swing.JButton();
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 10), new java.awt.Dimension(0, 10), new java.awt.Dimension(32767, 10));
        BoutonViderPanier = new javax.swing.JButton();
        spaceButton = new javax.swing.Box.Filler(new java.awt.Dimension(0, 200), new java.awt.Dimension(0, 200), new java.awt.Dimension(250, 200));
        BoutonValiderPanier = new javax.swing.JButton();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(30, 200), new java.awt.Dimension(30, 200), new java.awt.Dimension(30, 200));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InterfacePanier.setBackground(new java.awt.Color(255, 255, 255));
        java.awt.GridBagLayout InterfacePanierLayout = new java.awt.GridBagLayout();
        InterfacePanierLayout.columnWidths = new int[] {0};
        InterfacePanierLayout.rowHeights = new int[] {0};
        InterfacePanierLayout.columnWeights = new double[] {0.0};
        InterfacePanierLayout.rowWeights = new double[] {0.0};
        InterfacePanier.setLayout(InterfacePanierLayout);
        InterfacePanier.add(filler6, new java.awt.GridBagConstraints());

        Colonne1.setLayout(new javax.swing.BoxLayout(Colonne1, javax.swing.BoxLayout.Y_AXIS));

        choixRecette.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        choixRecette.setForeground(new java.awt.Color(141, 126, 255));
        choixRecette.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recettes", "Cake au citron", "Ganache à l'amande", "Délice parfait", "Tarte aux pommes", "Chausson aux cerises griottes", " " }));
        choixRecette.setMaximumSize(new java.awt.Dimension(200, 50));
        choixRecette.setMinimumSize(new java.awt.Dimension(200, 22));
        choixRecette.setPreferredSize(new java.awt.Dimension(200, 22));
        choixRecette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choixRecetteActionPerformed(evt);
            }
        });
        Colonne1.add(choixRecette);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        Colonne1.add(jSeparator1);

        ScrollPaneRecettes.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPaneRecettes.setMaximumSize(new java.awt.Dimension(200, 300));
        ScrollPaneRecettes.setMinimumSize(new java.awt.Dimension(200, 300));
        ScrollPaneRecettes.setPreferredSize(new java.awt.Dimension(200, 300));

        afficheRecette.setEditable(false);
        afficheRecette.setBackground(new java.awt.Color(255, 255, 255));
        afficheRecette.setColumns(20);
        afficheRecette.setFont(new java.awt.Font("Eunjin Nakseo", 0, 15)); // NOI18N
        afficheRecette.setForeground(new java.awt.Color(189, 98, 199));
        afficheRecette.setRows(5);
        afficheRecette.setMaximumSize(new java.awt.Dimension(200, 300));
        afficheRecette.setMinimumSize(new java.awt.Dimension(200, 300));
        ScrollPaneRecettes.setViewportView(afficheRecette);

        Colonne1.add(ScrollPaneRecettes);

        InterfacePanier.add(Colonne1, new java.awt.GridBagConstraints());
        InterfacePanier.add(filler3, new java.awt.GridBagConstraints());

        Colonne2.setBackground(new java.awt.Color(255, 255, 255));
        Colonne2.setMaximumSize(new java.awt.Dimension(300, 400));
        Colonne2.setMinimumSize(new java.awt.Dimension(300, 400));
        Colonne2.setPreferredSize(new java.awt.Dimension(300, 416));
        Colonne2.setLayout(new javax.swing.BoxLayout(Colonne2, javax.swing.BoxLayout.Y_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 50));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel1.setPreferredSize(new java.awt.Dimension(117, 21));

        labelVotrePanier.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        labelVotrePanier.setForeground(new java.awt.Color(189, 98, 199));
        labelVotrePanier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelVotrePanier.setText("Votre panier :");
        labelVotrePanier.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(labelVotrePanier);

        Colonne2.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 300));
        jPanel2.setMinimumSize(new java.awt.Dimension(26, 150));
        jPanel2.setPreferredSize(new java.awt.Dimension(200, 330));
        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        ScrollPanePanier.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        ScrollPanePanier.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        ScrollPanePanier.setMaximumSize(new java.awt.Dimension(250, 300));
        ScrollPanePanier.setMinimumSize(new java.awt.Dimension(250, 300));
        ScrollPanePanier.setPreferredSize(new java.awt.Dimension(250, 300));

        affichePanier.setEditable(false);
        affichePanier.setBackground(new java.awt.Color(255, 255, 255));
        affichePanier.setColumns(20);
        affichePanier.setFont(new java.awt.Font("Eunjin Nakseo", 0, 15)); // NOI18N
        affichePanier.setForeground(new java.awt.Color(141, 126, 255));
        affichePanier.setRows(5);
        affichePanier.setMaximumSize(new java.awt.Dimension(250, 300));
        affichePanier.setMinimumSize(new java.awt.Dimension(250, 300));
        affichePanier.setPreferredSize(new java.awt.Dimension(250, 300));
        ScrollPanePanier.setViewportView(affichePanier);

        jPanel2.add(ScrollPanePanier);

        Colonne2.add(jPanel2);

        LigneTotalPanier.setBackground(new java.awt.Color(255, 255, 255));
        LigneTotalPanier.setMaximumSize(new java.awt.Dimension(200, 30));
        LigneTotalPanier.setMinimumSize(new java.awt.Dimension(200, 30));
        LigneTotalPanier.setPreferredSize(new java.awt.Dimension(104, 30));
        LigneTotalPanier.setLayout(new java.awt.GridLayout(1, 2));

        LabelTotalPanier.setForeground(new java.awt.Color(141, 126, 255));
        LabelTotalPanier.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelTotalPanier.setText("Total :");
        LabelTotalPanier.setMaximumSize(new java.awt.Dimension(40, 30));
        LabelTotalPanier.setMinimumSize(new java.awt.Dimension(40, 30));
        LabelTotalPanier.setPreferredSize(new java.awt.Dimension(40, 30));
        LigneTotalPanier.add(LabelTotalPanier);

        LabelPrixTotal.setBackground(new java.awt.Color(255, 255, 255));
        LabelPrixTotal.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        LabelPrixTotal.setForeground(new java.awt.Color(189, 98, 199));
        LabelPrixTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        LabelPrixTotal.setText("00,00 €");
        LabelPrixTotal.setMaximumSize(new java.awt.Dimension(52, 30));
        LabelPrixTotal.setMinimumSize(new java.awt.Dimension(52, 30));
        LabelPrixTotal.setPreferredSize(new java.awt.Dimension(52, 30));
        LigneTotalPanier.add(LabelPrixTotal);

        Colonne2.add(LigneTotalPanier);

        InterfacePanier.add(Colonne2, new java.awt.GridBagConstraints());
        InterfacePanier.add(filler4, new java.awt.GridBagConstraints());

        Colonne3.setBackground(new java.awt.Color(255, 255, 255));
        Colonne3.setLayout(new javax.swing.BoxLayout(Colonne3, javax.swing.BoxLayout.Y_AXIS));

        BoutonAjouterFruit.setBackground(new java.awt.Color(141, 126, 255));
        BoutonAjouterFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 15)); // NOI18N
        BoutonAjouterFruit.setForeground(new java.awt.Color(255, 255, 255));
        BoutonAjouterFruit.setText("Ajouter un fruit");
        BoutonAjouterFruit.setMaximumSize(new java.awt.Dimension(155, 22));
        BoutonAjouterFruit.setMinimumSize(new java.awt.Dimension(155, 22));
        BoutonAjouterFruit.setPreferredSize(new java.awt.Dimension(137, 22));
        Colonne3.add(BoutonAjouterFruit);
        Colonne3.add(filler1);

        BoutonRetirerFruit.setBackground(new java.awt.Color(141, 126, 255));
        BoutonRetirerFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 15)); // NOI18N
        BoutonRetirerFruit.setForeground(new java.awt.Color(255, 255, 255));
        BoutonRetirerFruit.setText("Retirer un fruit");
        BoutonRetirerFruit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        BoutonRetirerFruit.setMaximumSize(new java.awt.Dimension(155, 22));
        BoutonRetirerFruit.setMinimumSize(new java.awt.Dimension(137, 22));
        BoutonRetirerFruit.setPreferredSize(new java.awt.Dimension(155, 22));
        Colonne3.add(BoutonRetirerFruit);
        Colonne3.add(filler2);

        BoutonViderPanier.setBackground(new java.awt.Color(141, 126, 255));
        BoutonViderPanier.setFont(new java.awt.Font("Eunjin Nakseo", 0, 15)); // NOI18N
        BoutonViderPanier.setForeground(new java.awt.Color(255, 255, 255));
        BoutonViderPanier.setText("Vider le panier");
        BoutonViderPanier.setMaximumSize(new java.awt.Dimension(155, 22));
        BoutonViderPanier.setMinimumSize(new java.awt.Dimension(137, 22));
        BoutonViderPanier.setPreferredSize(new java.awt.Dimension(155, 22));
        Colonne3.add(BoutonViderPanier);
        Colonne3.add(spaceButton);

        BoutonValiderPanier.setBackground(new java.awt.Color(189, 98, 199));
        BoutonValiderPanier.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        BoutonValiderPanier.setForeground(new java.awt.Color(255, 255, 255));
        BoutonValiderPanier.setText("Valider le panier");
        BoutonValiderPanier.setMaximumSize(new java.awt.Dimension(155, 32));
        BoutonValiderPanier.setMinimumSize(new java.awt.Dimension(155, 32));
        BoutonValiderPanier.setPreferredSize(new java.awt.Dimension(155, 32));
        BoutonValiderPanier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonValiderPanierActionPerformed(evt);
            }
        });
        Colonne3.add(BoutonValiderPanier);

        InterfacePanier.add(Colonne3, new java.awt.GridBagConstraints());
        InterfacePanier.add(filler5, new java.awt.GridBagConstraints());

        getContentPane().add(InterfacePanier, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonValiderPanierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonValiderPanierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonValiderPanierActionPerformed

    private void choixRecetteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choixRecetteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_choixRecetteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //Interface panier = new Interface(this, true, JList<String> listeFruits, double prixTotal);

                Interface panier = new Interface(new javax.swing.JFrame(), true);
                panier.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                panier.setVisible(true);
            }
        });
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonAjouterFruit;
    private javax.swing.JButton BoutonRetirerFruit;
    private javax.swing.JButton BoutonValiderPanier;
    private javax.swing.JButton BoutonViderPanier;
    private javax.swing.JPanel Colonne1;
    private javax.swing.JPanel Colonne2;
    private javax.swing.JPanel Colonne3;
    private javax.swing.JPanel InterfacePanier;
    private javax.swing.JLabel LabelPrixTotal;
    private javax.swing.JLabel LabelTotalPanier;
    private javax.swing.JPanel LigneTotalPanier;
    private javax.swing.JScrollPane ScrollPanePanier;
    private javax.swing.JScrollPane ScrollPaneRecettes;
    private javax.swing.JTextArea affichePanier;
    private javax.swing.JTextArea afficheRecette;
    private javax.swing.JComboBox<String> choixRecette;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.Box.Filler filler3;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler5;
    private javax.swing.Box.Filler filler6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelVotrePanier;
    private javax.swing.Box.Filler spaceButton;
    // End of variables declaration//GEN-END:variables
}
