/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.views;

import java.net.URL;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import fr.ufrsciencestech.exceptions.PanierPleinException;
import fr.ufrsciencestech.models.Panier;
import fr.ufrsciencestech.models.fruits.Fruit;
import fr.ufrsciencestech.models.recettes.Recette;

/**
 *
 * @author hg186648
 */
public class PageFruit extends javax.swing.JDialog {

    private Panier panier;
    private Fruit fruit;
    
    private ArrayList<Recette> listeRecette; //Recettes contenant ce fruit
    private URL iF; //chemin pour accéder à l'image du fruit 
    
    /**
     * Creates new PageFruit
     * @param parent
     * @param modal
     */
    //public PageFruit(java.awt.Frame parent, boolean modal,Fruit leFruit) {
    public PageFruit(java.awt.Frame parent, boolean modal, Fruit f, Panier p) {
        super(parent, modal);
        this.panier = p;
        this.fruit = f;
        this.iF= this.getClass().getClassLoader().getResource("./images/" + f.getName() + ".png");
        initComponents();
        initFruitIHM();
        
    }

    public void initFruitIHM(){
        this.ImageFruit.setIcon(new ImageIcon(iF));
        this.NomFruit.setText(fruit.getName());
        this.OrigineFruit.setText(fruit.getOrigine());
        this.PrixFruit.setText(Double.toString(fruit.getPrix()));
        this.NbFruit.setText(Integer.toString(1));
        this.TotalFruit.setText(Double.toString(Double.parseDouble(this.NbFruit.getText()) * fruit.getPrix()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ligne1 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        ImageFruit = new javax.swing.JButton();
        PanelInfoFruit = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NomFruit = new javax.swing.JLabel();
        Ligne2Infos = new javax.swing.JPanel();
        LabelOrigine = new javax.swing.JLabel();
        OrigineFruit = new javax.swing.JLabel();
        Ligne3Infos = new javax.swing.JPanel();
        LabelPrix = new javax.swing.JLabel();
        PrixFruit = new javax.swing.JLabel();
        EuroFruit = new javax.swing.JLabel();
        Ligne2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LabelExempleRecettes = new javax.swing.JLabel();
        ExempleRecette = new javax.swing.JLabel();
        Ligne3 = new javax.swing.JPanel();
        PanelNombreFruit = new javax.swing.JPanel();
        MoinsFruit = new javax.swing.JButton();
        NbFruit = new javax.swing.JTextField();
        PlusFruit = new javax.swing.JButton();
        PanelTotalFruit = new javax.swing.JPanel();
        TotalFruit = new javax.swing.JLabel();
        EuroTotal = new javax.swing.JLabel();
        AjoutFruit = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(460, 325));
        setMinimumSize(new java.awt.Dimension(460, 318));
        setPreferredSize(new java.awt.Dimension(460, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        Ligne1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 125));

        ImageFruit.setForeground(new java.awt.Color(255, 255, 255));
        ImageFruit.setEnabled(false);
        ImageFruit.setPreferredSize(new java.awt.Dimension(125, 125));
        jPanel1.add(ImageFruit);

        Ligne1.add(jPanel1);

        PanelInfoFruit.setLayout(new javax.swing.BoxLayout(PanelInfoFruit, javax.swing.BoxLayout.Y_AXIS));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 25));

        NomFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        NomFruit.setForeground(new java.awt.Color(141, 126, 255));
        NomFruit.setText("Fruit");
        jPanel2.add(NomFruit);

        PanelInfoFruit.add(jPanel2);

        Ligne2Infos.setBackground(new java.awt.Color(255, 255, 255));

        LabelOrigine.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        LabelOrigine.setForeground(new java.awt.Color(141, 126, 255));
        LabelOrigine.setText("Origine : ");
        Ligne2Infos.add(LabelOrigine);

        OrigineFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        OrigineFruit.setForeground(new java.awt.Color(189, 98, 199));
        OrigineFruit.setText("Pays");
        Ligne2Infos.add(OrigineFruit);

        PanelInfoFruit.add(Ligne2Infos);

        Ligne3Infos.setBackground(new java.awt.Color(255, 255, 255));

        LabelPrix.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        LabelPrix.setForeground(new java.awt.Color(141, 126, 255));
        LabelPrix.setText("Prix : ");
        Ligne3Infos.add(LabelPrix);

        PrixFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        PrixFruit.setForeground(new java.awt.Color(189, 98, 199));
        PrixFruit.setText("00,00");
        Ligne3Infos.add(PrixFruit);

        EuroFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        EuroFruit.setForeground(new java.awt.Color(189, 98, 199));
        EuroFruit.setText(" €");
        Ligne3Infos.add(EuroFruit);

        PanelInfoFruit.add(Ligne3Infos);

        Ligne1.add(PanelInfoFruit);

        getContentPane().add(Ligne1);

        Ligne2.setPreferredSize(new java.awt.Dimension(100, 70));
        Ligne2.setLayout(new javax.swing.BoxLayout(Ligne2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(378, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        LabelExempleRecettes.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        LabelExempleRecettes.setForeground(new java.awt.Color(141, 126, 255));
        LabelExempleRecettes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelExempleRecettes.setText("Exemples de recettes :");
        jPanel3.add(LabelExempleRecettes);

        ExempleRecette.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        ExempleRecette.setForeground(new java.awt.Color(189, 98, 199));
        ExempleRecette.setText("recette, recette, recette");
        ExempleRecette.setToolTipText("");
        jPanel3.add(ExempleRecette);

        Ligne2.add(jPanel3);

        getContentPane().add(Ligne2);

        Ligne3.setPreferredSize(new java.awt.Dimension(350, 40));
        Ligne3.setLayout(new java.awt.GridLayout(1, 2));

        PanelNombreFruit.setBackground(new java.awt.Color(255, 255, 255));
        PanelNombreFruit.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        MoinsFruit.setBackground(new java.awt.Color(141, 126, 255));
        MoinsFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        MoinsFruit.setForeground(new java.awt.Color(255, 255, 255));
        MoinsFruit.setText("-");
        MoinsFruit.setMaximumSize(new java.awt.Dimension(37, 37));
        MoinsFruit.setMinimumSize(new java.awt.Dimension(37, 37));
        MoinsFruit.setPreferredSize(new java.awt.Dimension(37, 37));
        MoinsFruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoinsFruitMouseClicked(evt);
            }
        });
        PanelNombreFruit.add(MoinsFruit);

        NbFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        NbFruit.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NbFruit.setText("0");
        NbFruit.setMaximumSize(new java.awt.Dimension(30, 37));
        NbFruit.setMinimumSize(new java.awt.Dimension(64, 37));
        NbFruit.setPreferredSize(new java.awt.Dimension(64, 37));
        PanelNombreFruit.add(NbFruit);

        PlusFruit.setBackground(new java.awt.Color(141, 126, 255));
        PlusFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        PlusFruit.setForeground(new java.awt.Color(255, 255, 255));
        PlusFruit.setText("+");
        PlusFruit.setMaximumSize(new java.awt.Dimension(37, 37));
        PlusFruit.setMinimumSize(new java.awt.Dimension(37, 37));
        PlusFruit.setPreferredSize(new java.awt.Dimension(37, 37));
        PlusFruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlusFruitMouseClicked(evt);
            }
        });
        PanelNombreFruit.add(PlusFruit);

        Ligne3.add(PanelNombreFruit);

        PanelTotalFruit.setBackground(new java.awt.Color(255, 255, 255));
        PanelTotalFruit.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        TotalFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        TotalFruit.setForeground(new java.awt.Color(189, 98, 199));
        TotalFruit.setText("00,00");
        PanelTotalFruit.add(TotalFruit);

        EuroTotal.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        EuroTotal.setForeground(new java.awt.Color(189, 98, 199));
        EuroTotal.setText(" € ");
        PanelTotalFruit.add(EuroTotal);

        AjoutFruit.setBackground(new java.awt.Color(189, 98, 199));
        AjoutFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        AjoutFruit.setForeground(new java.awt.Color(255, 255, 255));
        AjoutFruit.setText("Ajouter");
        AjoutFruit.setPreferredSize(new java.awt.Dimension(89, 32));
        AjoutFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutFruitActionPerformed(evt);
            }
        });
        PanelTotalFruit.add(AjoutFruit);

        Ligne3.add(PanelTotalFruit);

        getContentPane().add(Ligne3);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void actualiserPrixTotal() {
        this.TotalFruit.setText(Double.toString(Double.parseDouble(this.NbFruit.getText()) * fruit.getPrix()));
    }

    private void MoinsFruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoinsFruitMouseClicked
        int nombre = Integer.parseInt(this.NbFruit.getText());
        //TODO VERIFIER SI OK
        if(nombre == 1) //Vérification qu'on ne peut avoir un chiffre négatif
        {
            this.NbFruit.setText(Integer.toString(nombre));
        }
        else 
        {            
            nombre--;
            this.NbFruit.setText(Integer.toString(nombre));
        }
        
        //Mise à jour du prix total
        actualiserPrixTotal();
    }//GEN-LAST:event_MoinsFruitMouseClicked

    private void PlusFruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlusFruitMouseClicked
        int nombre = Integer.parseInt(this.NbFruit.getText());
        nombre++;
        this.NbFruit.setText(Integer.toString(nombre));
        
        //Mise à jour du prix total
        actualiserPrixTotal();
    }//GEN-LAST:event_PlusFruitMouseClicked

    private void AjoutFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutFruitActionPerformed
        
        int nombre = Integer.parseInt(this.NbFruit.getText());
        int i = 0;
        try {
            for (; i < nombre; i++) {
                panier.ajout(fruit);
            }
        } catch (PanierPleinException e) {
            JOptionPane.showMessageDialog(Ligne2, "Il n'y a plus de place dans votre panier.\nSeulement " + i + " " + fruit.getName() + " se retrouvent dans votre panier.", "Attention !", JOptionPane.ERROR_MESSAGE);

        }finally {
            this.dispose();
        }
    }//GEN-LAST:event_AjoutFruitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutFruit;
    private javax.swing.JLabel EuroFruit;
    private javax.swing.JLabel EuroTotal;
    private javax.swing.JLabel ExempleRecette;
    private javax.swing.JButton ImageFruit;
    private javax.swing.JLabel LabelExempleRecettes;
    private javax.swing.JLabel LabelOrigine;
    private javax.swing.JLabel LabelPrix;
    private javax.swing.JPanel Ligne1;
    private javax.swing.JPanel Ligne2;
    private javax.swing.JPanel Ligne2Infos;
    private javax.swing.JPanel Ligne3;
    private javax.swing.JPanel Ligne3Infos;
    private javax.swing.JButton MoinsFruit;
    private javax.swing.JTextField NbFruit;
    private javax.swing.JLabel NomFruit;
    private javax.swing.JLabel OrigineFruit;
    private javax.swing.JPanel PanelInfoFruit;
    private javax.swing.JPanel PanelNombreFruit;
    private javax.swing.JPanel PanelTotalFruit;
    private javax.swing.JButton PlusFruit;
    private javax.swing.JLabel PrixFruit;
    private javax.swing.JLabel TotalFruit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
