/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package fr.ufrsciencestech.views;

import java.net.URL;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import fr.ufrsciencestech.exceptions.PanierPleinException;
import fr.ufrsciencestech.models.Panier;
import fr.ufrsciencestech.models.fruits.*;
import fr.ufrsciencestech.models.recettes.Recette;

/**
 *
 * @author hg186648
 */
public class PageRecette extends javax.swing.JDialog {

    private Panier panier;
    private Recette recette;
    
    private ArrayList<Fruit> listeFruit; //Fruits nécessaires de la recette
    private URL iR; //chemin pour accéder à l'image de la recette
    
    /**
     * Creates new PageFruit
     * @param parent
     * @param modal
     */
    
    public PageRecette(java.awt.Frame parent, boolean modal, Recette r, Panier p) {
        super(parent, modal);
        this.panier = p;
        this.recette = r;
        //this.iR= this.getClass().getClassLoader().getResource("./images/" + r.getName() + ".png");
        initComponents();
        initRecetteIHM();
        
    }

    private void initRecetteIHM(){
        //this.ImageRecette.setIcon(new ImageIcon(iR));
        this.NomRecette.setText(recette.getName());
        this.NbRecette.setText(Integer.toString(1));
        
        //this.Etapes.setText(recette.getDescription());
        
        
        //this.TotalFruit.setText(Double.toString(Double.parseDouble(this.NbFruit.getText()) * recette.getPrix()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Ligne1 = new javax.swing.JPanel();
        ImagePanel = new javax.swing.JPanel();
        ImageRecette = new javax.swing.JButton();
        PanelInfoRecette = new javax.swing.JPanel();
        Ligne1Infos = new javax.swing.JPanel();
        NomRecette = new javax.swing.JLabel();
        Ligne2Infos = new javax.swing.JPanel();
        LabelIngredients = new javax.swing.JLabel();
        IngredientsRecette = new javax.swing.JLabel();
        Ligne2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        LabelEtapes = new javax.swing.JLabel();
        Etapes = new javax.swing.JLabel();
        Ligne3 = new javax.swing.JPanel();
        PanelNombreFruit = new javax.swing.JPanel();
        MoinsFruit = new javax.swing.JButton();
        NbRecette = new javax.swing.JTextField();
        PlusFruit = new javax.swing.JButton();
        PanelTotalFruit = new javax.swing.JPanel();
        TotalFruit = new javax.swing.JLabel();
        EuroTotal = new javax.swing.JLabel();
        AjoutFruit = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(460, 318));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));

        Ligne1.setLayout(new java.awt.GridLayout(1, 2));

        ImagePanel.setBackground(new java.awt.Color(255, 255, 255));
        ImagePanel.setPreferredSize(new java.awt.Dimension(100, 125));

        ImageRecette.setForeground(new java.awt.Color(255, 255, 255));
        ImageRecette.setPreferredSize(new java.awt.Dimension(125, 125));
        ImagePanel.add(ImageRecette);

        Ligne1.add(ImagePanel);

        PanelInfoRecette.setLayout(new javax.swing.BoxLayout(PanelInfoRecette, javax.swing.BoxLayout.Y_AXIS));

        Ligne1Infos.setBackground(new java.awt.Color(255, 255, 255));
        Ligne1Infos.setPreferredSize(new java.awt.Dimension(100, 25));

        NomRecette.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        NomRecette.setForeground(new java.awt.Color(141, 126, 255));
        NomRecette.setText("Recette");
        Ligne1Infos.add(NomRecette);

        PanelInfoRecette.add(Ligne1Infos);

        Ligne2Infos.setBackground(new java.awt.Color(255, 255, 255));

        LabelIngredients.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        LabelIngredients.setForeground(new java.awt.Color(141, 126, 255));
        LabelIngredients.setText("Ingrédients  : ");
        Ligne2Infos.add(LabelIngredients);

        IngredientsRecette.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        IngredientsRecette.setForeground(new java.awt.Color(189, 98, 199));
        IngredientsRecette.setText("Les ingrédients");
        Ligne2Infos.add(IngredientsRecette);

        PanelInfoRecette.add(Ligne2Infos);

        Ligne1.add(PanelInfoRecette);

        getContentPane().add(Ligne1);

        Ligne2.setPreferredSize(new java.awt.Dimension(100, 70));
        Ligne2.setLayout(new javax.swing.BoxLayout(Ligne2, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMinimumSize(new java.awt.Dimension(378, 100));
        jPanel3.setPreferredSize(new java.awt.Dimension(100, 80));
        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 25));

        LabelEtapes.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        LabelEtapes.setForeground(new java.awt.Color(141, 126, 255));
        LabelEtapes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelEtapes.setText("Étapes :");
        jPanel3.add(LabelEtapes);

        Etapes.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        Etapes.setForeground(new java.awt.Color(189, 98, 199));
        Etapes.setText("1,2,3");
        Etapes.setToolTipText("");
        jPanel3.add(Etapes);

        Ligne2.add(jPanel3);

        getContentPane().add(Ligne2);

        Ligne3.setPreferredSize(new java.awt.Dimension(350, 40));
        Ligne3.setLayout(new java.awt.GridLayout(1, 2));

        PanelNombreFruit.setBackground(new java.awt.Color(255, 255, 255));
        PanelNombreFruit.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        MoinsFruit.setBackground(new java.awt.Color(141, 126, 255));
        MoinsFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        MoinsFruit.setForeground(new java.awt.Color(255, 255, 255));
        MoinsFruit.setText("-");
        MoinsFruit.setMaximumSize(new java.awt.Dimension(37, 37));
        MoinsFruit.setMinimumSize(new java.awt.Dimension(37, 37));
        MoinsFruit.setPreferredSize(new java.awt.Dimension(37, 37));
        MoinsFruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MoinsFruitMouseClicked(evt);
            }
        });
        PanelNombreFruit.add(MoinsFruit);

        NbRecette.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        NbRecette.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        NbRecette.setText("0");
        NbRecette.setMaximumSize(new java.awt.Dimension(30, 37));
        NbRecette.setMinimumSize(new java.awt.Dimension(64, 37));
        NbRecette.setPreferredSize(new java.awt.Dimension(64, 37));
        PanelNombreFruit.add(NbRecette);

        PlusFruit.setBackground(new java.awt.Color(141, 126, 255));
        PlusFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        PlusFruit.setForeground(new java.awt.Color(255, 255, 255));
        PlusFruit.setText("+");
        PlusFruit.setMaximumSize(new java.awt.Dimension(37, 37));
        PlusFruit.setMinimumSize(new java.awt.Dimension(37, 37));
        PlusFruit.setPreferredSize(new java.awt.Dimension(37, 37));
        PlusFruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlusFruitMouseClicked(evt);
            }
        });
        PanelNombreFruit.add(PlusFruit);

        Ligne3.add(PanelNombreFruit);

        PanelTotalFruit.setBackground(new java.awt.Color(255, 255, 255));
        PanelTotalFruit.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        TotalFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        TotalFruit.setForeground(new java.awt.Color(189, 98, 199));
        TotalFruit.setText("00,00");
        PanelTotalFruit.add(TotalFruit);

        EuroTotal.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        EuroTotal.setForeground(new java.awt.Color(189, 98, 199));
        EuroTotal.setText(" € ");
        PanelTotalFruit.add(EuroTotal);

        AjoutFruit.setBackground(new java.awt.Color(189, 98, 199));
        AjoutFruit.setFont(new java.awt.Font("Eunjin Nakseo", 0, 16)); // NOI18N
        AjoutFruit.setForeground(new java.awt.Color(255, 255, 255));
        AjoutFruit.setText("Ajouter");
        AjoutFruit.setPreferredSize(new java.awt.Dimension(89, 32));
        AjoutFruit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjoutFruitActionPerformed(evt);
            }
        });
        PanelTotalFruit.add(AjoutFruit);

        Ligne3.add(PanelTotalFruit);

        getContentPane().add(Ligne3);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    

    private void actualiserPrixTotal() {
       // this.TotalFruit.setText(Double.toString(Double.parseDouble(this.NbRecette.getText()) * fruit.getPrix()));
    }

    private void MoinsFruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MoinsFruitMouseClicked
        int nombre = Integer.parseInt(this.NbRecette.getText());
        //TODO VERIFIER SI OK
        if(nombre == 1) //Vérification qu'on ne peut avoir un chiffre négatif
        {
            this.NbRecette.setText(Integer.toString(nombre));
        }
        else 
        {            
            nombre--;
            this.NbRecette.setText(Integer.toString(nombre));
        }
        
        //Mise à jour du prix total
        actualiserPrixTotal();
    }//GEN-LAST:event_MoinsFruitMouseClicked

    private void PlusFruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlusFruitMouseClicked
        int nombre = Integer.parseInt(this.NbRecette.getText());
        nombre++;
        this.NbRecette.setText(Integer.toString(nombre));
        
        //Mise à jour du prix total
        actualiserPrixTotal();
    }//GEN-LAST:event_PlusFruitMouseClicked

    private void AjoutFruitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjoutFruitActionPerformed
        Fruit fruit = new Pomme();
        
        int nombre = Integer.parseInt(this.NbRecette.getText());
        int i = 0;
        try {
            for (; i < nombre; i++) {
                panier.ajout(fruit);
            }
        } catch (PanierPleinException e) {
            JOptionPane.showMessageDialog(Ligne2, "Il n'y a pas assez de place dans votre panier.", "Faites du tri !", JOptionPane.ERROR_MESSAGE);

        }finally {
            this.dispose();
        }
        
    }//GEN-LAST:event_AjoutFruitActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AjoutFruit;
    private javax.swing.JLabel Etapes;
    private javax.swing.JLabel EuroTotal;
    private javax.swing.JPanel ImagePanel;
    private javax.swing.JButton ImageRecette;
    private javax.swing.JLabel IngredientsRecette;
    private javax.swing.JLabel LabelEtapes;
    private javax.swing.JLabel LabelIngredients;
    private javax.swing.JPanel Ligne1;
    private javax.swing.JPanel Ligne1Infos;
    private javax.swing.JPanel Ligne2;
    private javax.swing.JPanel Ligne2Infos;
    private javax.swing.JPanel Ligne3;
    private javax.swing.JButton MoinsFruit;
    private javax.swing.JTextField NbRecette;
    private javax.swing.JLabel NomRecette;
    private javax.swing.JPanel PanelInfoRecette;
    private javax.swing.JPanel PanelNombreFruit;
    private javax.swing.JPanel PanelTotalFruit;
    private javax.swing.JButton PlusFruit;
    private javax.swing.JLabel TotalFruit;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
